### ISSUE TITLE
Configuration only accepts walltimes smaller than 24h

### ISSUE THREAD

**Issue by ppsbs** [BeyondTheClouds/enoslib#90]
Hi,

Whenever I try to create a reservation longer than 24h using a Configuration I receive a value error. Code and error available bellow. 

Thanks! 
Pedro

from enoslib.infra.enos_g5k.configuration import Configuration
conf = Configuration.from_settings(job_type="deploy",
                                       job_name='pedros',
                                       walltime='36:00:00',
                                env_name="http://public.nancy.grid5000.fr/~psilva/edge_cloud_image.dsc")

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "exp_plat/__main__.py", line 262, in <module>
    deploy_on_g5k(*(sys.argv[2:]))
  File "exp_plat/__main__.py", line 43, in deploy_on_g5k
    n_vm_hosts, n_fronts, n_producers, cluster, site, walltime)
  File "exp_plat/util/vm_manager.py", line 101, in reserve_and_deploy
    roles, networks = provider.init()
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/provider.py", line 73, in init
    r.launch()
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/api.py", line 87, in launch
    self.reserve()
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/api.py", line 95, in reserve
    nodes, networks = self.driver.reserve()
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/driver.py", line 127, in reserve
    self.networks,
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/utils.py", line 52, in grid_get_or_create_job
    job_name, walltime, reservation_date, queue, job_type, machines, networks
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/utils.py", line 228, in grid_make_reservation
    reservation_date = g5k_api_utils._do_synchronise_jobs(walltime, machines)
  File "/home/psilva/.local/lib/python3.5/site-packages/enoslib/infra/enos_g5k/g5k_api_utils.py", line 695, in _do_synchronise_jobs
    _t = time.strptime(walltime, "%H:%M:%S")
  File "/usr/lib/python3.5/_strptime.py", line 504, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '36:00:00' does not match format '%H:%M:%S'

**Comment by msimonin** [comment]
https://gitlab.inria.fr/discovery/enoslib/issues/33

**Comment by msimonin** [comment]
fixed in 4.3.1
